### ISSUE TITLE
Crear Nuevo Modelo Empresa

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/digiAgenda#12]
Crear un modelo dentro de la app contacts, la cual debe ser nombrada "Empresa".

Campos que debe contener:
- **nombre**: Es el nombre oficial de la empresa 
- **giro**: Tipo de empresa (Tecnología, Alimentos, Servicios, etc)
- **tipo**: (AGUA, FUEGO, AIRE, TIERRA)

Nota: **tipo** debe ser una lista predefinida.

**Comment by JBasilio24** [comment]
Listo ;)

**Comment by RamsesMartinez** [comment]
Añadido en Pull Request => https://github.com/DigimundoTesca/digiAgenda/pull/21
