### ISSUE TITLE
Eliminar carpeta media

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/digiAgenda#16]
En el commit https://github.com/DigimundoTesca/digiAgenda/commit/9ee52023dc27be713c28b522e0020d4017861f5a se subio la carpeta media de django, hay que elimnar su contenido y crear un commit, después, en el siguiente commit ignorrar esa carpeta en el .gitignore

**Comment by HanzelAR** [comment]
yo hice unos commit para eliminar la carpeta

**Comment by RamsesMartinez** [comment]
Excelente :+1: 
Issue solucionado en PR https://github.com/DigimundoTesca/digiAgenda/pull/17
