### ISSUE TITLE
Modificar el modelo Empresas

### ISSUE THREAD

**Issue by JBasilio24** [DigimundoTesca/digiAgenda#23]
cambiar el campo de direcciones del modelo contacto a empresas

**Comment by JBasilio24** [comment]
listo

**Comment by RamsesMartinez** [comment]
Por favor coloca el commit donde se solucionó

**Comment by JBasilio24** [comment]
Solucionado en commit => https://github.com/DigimundoTesca/digiAgenda/commit/83d9533d7a81cb793ab23863dc23d4fd4de4438d

**Comment by RamsesMartinez** [comment]
Cierro issue y abro uno nuevo para que comenter los campos del modelo del contacto que ya no estarán después.
