### ISSUE TITLE
Comentar codigo que sera borrado

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/digiAgenda#27]
Hay campos que serán eliminados del modelo Cliente y serán pasados al modelo Empresa.
Hay que comentar esto en el mismo modelo para que no haya confusión a futuro, ya sea que se comente cada campo a eliminar o al principio.

**Comment by JBasilio24** [comment]
hecho https://github.com/DigimundoTesca/digiAgenda/commit/5e10c7fbd77106e48455bad981b288f57c9650a3
